name: flutter_redux_navigation
description: A simple reactive navigation middleware for Flutter's redux library.
version: 0.3.0
author: Efthymios Sarmpanis <e.sarbanis@gmail.com>
homepage: https://github.com/flutterings/flutter_redux_navigation

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  redux: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
