name: flutter_redux_navigation
description: A simple reactive navigation middleware for Flutter's redux library.
version: 0.7.0
homepage: https://github.com/flutterings/flutter_redux_navigation

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  redux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.4

flutter:
